import re

def enforce_user_constraints(sql: str, question: str) -> str:
    """
    Deterministic guardrail layer to fix SQL generated by LLM.
    Enforces user constraints that the LLM might have missed.
    """
    q = question.lower()

    # ---------- LIMIT ----------
    m = re.search(r'\b(limit|top|first)\s+(\d+)', q)
    if m:
        n = m.group(2)
        if re.search(r'\blimit\s+\d+\b', sql, re.I):
            sql = re.sub(r'\blimit\s+\d+\b', f'LIMIT {n}', sql, flags=re.I)
        else:
            sql = sql.rstrip(';') + f' LIMIT {n};'

    # ---------- DEPARTMENT ----------
    m = re.search(r'department\s+(\d+)', q)
    if m:
        dept = m.group(1)
        if not re.search(r'\bdept_id\s*=\s*'+dept+r'\b', sql, re.I):
            if re.search(r'\bwhere\b', sql, re.I):
                sql = re.sub(r'\bwhere\b', f'WHERE dept_id = {dept} AND ', sql, count=1, flags=re.I)
            else:
                sql = sql.replace(";", f" WHERE dept_id = {dept};")

    # ---------- TOP / HIGHEST ----------
    if any(w in q for w in ["top", "highest", "best"]):
        if "order by" not in sql.lower():
            sql = sql.rstrip(';') + " ORDER BY basic_salary DESC;"

    # ---------- AFTER YEAR ----------
    m = re.search(r'after\s+(\d{4})', q)
    if m:
        year = m.group(1)
        correct = f"'{year}-01-01'"
        sql = re.sub(r"'\d{4}-\d{2}-\d{2}'", correct, sql)
        # Also handle if no date was added
        if f"'{year}-01-01'" not in sql:
            if re.search(r'\bwhere\b', sql, re.I):
                sql = re.sub(r'\bwhere\b', f"WHERE join_date > '{year}-01-01' AND ", sql, count=1, flags=re.I)

    # ---------- SALARY FILTER ----------
    m = re.search(r'earn\s+more\s+than\s+(\d+)', q)
    if m:
        salary = m.group(1)
        if f'basic_salary > {salary}' not in sql.lower() and f'salary > {salary}' not in sql.lower():
            if re.search(r'\bwhere\b', sql, re.I):
                sql = re.sub(r'\bwhere\b', f'WHERE basic_salary > {salary} AND ', sql, count=1, flags=re.I)

    # ---------- INACTIVE / ACTIVE ----------
    if "inactive" in q:
        if "status='inactive'" not in sql.lower() and "status = 'inactive'" not in sql.lower():
            if re.search(r'\bwhere\b', sql, re.I):
                sql = re.sub(r'\bwhere\b', "WHERE status='inactive' AND ", sql, count=1, flags=re.I)
    elif "active" in q:
        if "status='active'" not in sql.lower() and "status = 'active'" not in sql.lower():
            if re.search(r'\bwhere\b', sql, re.I):
                sql = re.sub(r'\bwhere\b', "WHERE status='active' AND ", sql, count=1, flags=re.I)

    # ---------- DEVELOPER ROLE ----------
    if "developer" in q and "job_title" not in sql.lower():
        if re.search(r'\bwhere\b', sql, re.I):
            sql = re.sub(r'\bwhere\b', "WHERE job_title='Developer' AND ", sql, count=1, flags=re.I)

    # ---------- COMMON SCHEMA FIXUPS ----------
    # If the query selects `emp_name` from `salaries`, auto-join employees on emp_id.
    m = re.match(r'^\s*select\s+(?P<select>.*?)\s+from\s+salaries\b(?P<rest>.*)$', sql, flags=re.I | re.S)
    if m:
        select_part = m.group('select')
        rest = m.group('rest') or ""
        if re.search(r'\bemp_name\b', select_part, re.I) and not re.search(r'\bjoin\b', rest, re.I):
            fixed_select = select_part
            fixed_select = re.sub(r'(?<!\.)\bemp_id\b', 's.emp_id', fixed_select, flags=re.I)
            fixed_select = re.sub(r'(?<!\.)\bbasic_salary\b', 's.basic_salary', fixed_select, flags=re.I)
            fixed_select = re.sub(r'(?<!\.)\bbonus\b', 's.bonus', fixed_select, flags=re.I)
            fixed_select = re.sub(r'(?<!\.)\beffective_date\b', 's.effective_date', fixed_select, flags=re.I)
            fixed_select = re.sub(r'(?<!\.)\bemp_name\b', 'e.emp_name', fixed_select, flags=re.I)

            fixed_rest = re.sub(
                r'(?<!\.)\b(emp_id|basic_salary|bonus|effective_date)\b',
                r's.\1',
                rest,
                flags=re.I,
            )

            sql = f"SELECT {fixed_select} FROM salaries s JOIN employees e ON e.emp_id = s.emp_id{fixed_rest}"

    return sql
