import re
from dotenv import load_dotenv

load_dotenv(override=True)

from llm_client import call_llm

# Blocked operations
BLOCKED_PATTERNS = [
    r'\bDROP\b',
    r'\bDELETE\b',
    r'\bTRUNCATE\b',
    r'\bALTER\b',
    r'\bINSERT\b',
    r'\bUPDATE\b',
    r'\bGRANT\b',
    r'\bREVOKE\b',
    r'\bCREATE\s+TABLE\b',
    r'\bCREATE\s+DATABASE\b',
    r'\bTRUNCATE\b',
]


def validate_and_fix(sql, schema):
    """
    Validate and fix SQL query with security checks and schema validation.

    Returns: {
        valid: bool,
        sql: str (fixed or original),
        blocked: bool,
        reason: str or None,
        guardrail_events: list
    }
    """
    guardrail_events = []
    current_sql = sql.strip()

    # Check for destructive operations
    for pattern in BLOCKED_PATTERNS:
        if re.search(pattern, current_sql, re.IGNORECASE):
            return {
                "valid": False,
                "sql": current_sql,
                "blocked": True,
                "reason": "Destructive operation blocked",
                "guardrail_events": [{
                    "type": "blocked",
                    "action": "REJECTED",
                    "detail": f"Pattern '{pattern}' matched - destructive operation not allowed"
                }]
            }

    guardrail_events.append({
        "type": "info",
        "action": "PASSED",
        "detail": "Security check passed - no destructive operations detected"
    })

    # Check for missing LIMIT
    if not re.search(r'\bLIMIT\b', current_sql, re.IGNORECASE):
        current_sql = f"{current_sql} LIMIT 1000"
        guardrail_events.append({
            "type": "corrected",
            "action": "AUTO_FIXED",
            "detail": "Added LIMIT 1000 to prevent unbounded queries"
        })

    # Validate schema consistency
    schema_check = check_schema_consistency(current_sql, schema)
    if not schema_check["valid"]:
        fixed_sql = auto_fix_sql(current_sql, schema)
        if fixed_sql != current_sql:
            current_sql = fixed_sql
            guardrail_events.append({
                "type": "corrected",
                "action": "AUTO_FIXED",
                "detail": "Schema inconsistencies corrected via LLM"
            })

    return {
        "valid": True,
        "sql": current_sql,
        "blocked": False,
        "reason": None,
        "guardrail_events": guardrail_events
    }


def check_schema_consistency(sql, schema):
    """Check if table and column names exist in schema"""
    if "tables" not in schema:
        return {"valid": True}

    tables = schema["tables"]
    table_pattern = r'FROM\s+(\w+)|JOIN\s+(\w+)'
    referenced_tables = re.findall(table_pattern, sql, re.IGNORECASE)
    referenced_tables = [t[0] or t[1] for t in referenced_tables]

    for table in referenced_tables:
        if table.lower() not in [t.lower() for t in tables.keys()]:
            return {"valid": False, "error": f"Table '{table}' not found in schema"}

    return {"valid": True}


def auto_fix_sql(sql, schema):
    """Use LLM to fix SQL with schema issues"""
    schema_desc = "Available tables and columns:\n"
    if "tables" in schema:
        for table, info in schema["tables"].items():
            schema_desc += f"\nTable: {table}\n"
            if "columns" in info:
                for col in info["columns"]:
                    schema_desc += f"  - {col['name']} ({col.get('type', 'unknown')})\n"

    prompt = f"""You are a SQL corrector. The user wrote this SQL:
{sql}

Fix the SQL to use correct table and column names from the schema below.
Schema:
{schema_desc}

Return ONLY the corrected SQL. No explanation. No markdown. No backticks."""

    try:
        result = call_llm(prompt)
        return result.strip()
    except Exception as e:
        print(f"Error auto-fixing SQL: {e}")
        return sql


def enforce_user_constraints(sql: str, question: str) -> str:
    """
    Deterministic guardrail layer to fix SQL generated by LLM.
    Enforces user constraints that the LLM might have missed.
    """
    q = question.lower()

    # ---------- LIMIT ----------
    m = re.search(r'\b(limit|top|first)\s+(\d+)', q)
    if m:
        n = m.group(2)
        if re.search(r'\blimit\s+\d+\b', sql, re.I):
            sql = re.sub(r'\blimit\s+\d+\b', f'LIMIT {n}', sql, flags=re.I)
        else:
            sql = sql.rstrip(';') + f' LIMIT {n};'

    # ---------- DEPARTMENT ----------
    m = re.search(r'department\s+(\d+)', q)
    if m:
        dept = m.group(1)
        if not re.search(r'\bdept_id\s*=\s*'+dept+r'\b', sql, re.I):
            if re.search(r'\bwhere\b', sql, re.I):
                sql = re.sub(r'\bwhere\b', f'WHERE dept_id = {dept} AND ', sql, count=1, flags=re.I)
            else:
                sql = sql.replace(";", f" WHERE dept_id = {dept};")

    # ---------- TOP / HIGHEST ----------
    if any(w in q for w in ["top", "highest", "best"]):
        if "order by" not in sql.lower():
            sql = sql.rstrip(';') + " ORDER BY basic_salary DESC;"

    # ---------- AFTER YEAR ----------
    m = re.search(r'after\s+(\d{4})', q)
    if m:
        year = m.group(1)
        correct = f"'{year}-01-01'"
        sql = re.sub(r"'\d{4}-\d{2}-\d{2}'", correct, sql)
        # Also handle if no date was added
        if f"'{year}-01-01'" not in sql:
            if re.search(r'\bwhere\b', sql, re.I):
                sql = re.sub(r'\bwhere\b', f"WHERE join_date > '{year}-01-01' AND ", sql, count=1, flags=re.I)

    # ---------- SALARY FILTER ----------
    m = re.search(r'earn\s+more\s+than\s+(\d+)', q)
    if m:
        salary = m.group(1)
        if f'basic_salary > {salary}' not in sql.lower() and f'salary > {salary}' not in sql.lower():
            if re.search(r'\bwhere\b', sql, re.I):
                sql = re.sub(r'\bwhere\b', f'WHERE basic_salary > {salary} AND ', sql, count=1, flags=re.I)

    # ---------- INACTIVE / ACTIVE ----------
    if "inactive" in q:
        if "status='inactive'" not in sql.lower() and "status = 'inactive'" not in sql.lower():
            if re.search(r'\bwhere\b', sql, re.I):
                sql = re.sub(r'\bwhere\b', "WHERE status='inactive' AND ", sql, count=1, flags=re.I)
    elif "active" in q:
        if "status='active'" not in sql.lower() and "status = 'active'" not in sql.lower():
            if re.search(r'\bwhere\b', sql, re.I):
                sql = re.sub(r'\bwhere\b', "WHERE status='active' AND ", sql, count=1, flags=re.I)

    # ---------- DEVELOPER ROLE ----------
    if "developer" in q and "job_title" not in sql.lower():
        if re.search(r'\bwhere\b', sql, re.I):
            sql = re.sub(r'\bwhere\b', "WHERE job_title='Developer' AND ", sql, count=1, flags=re.I)

    # ---------- COMMON SCHEMA FIXUPS ----------
    # If the query selects `emp_name` from `salaries`, auto-join employees on emp_id.
    m = re.match(r'^\s*select\s+(?P<select>.*?)\s+from\s+salaries\b(?P<rest>.*)$', sql, flags=re.I | re.S)
    if m:
        select_part = m.group('select')
        rest = m.group('rest') or ""
        if re.search(r'\bemp_name\b', select_part, re.I) and not re.search(r'\bjoin\b', rest, re.I):
            fixed_select = select_part
            fixed_select = re.sub(r'(?<!\.)\bemp_id\b', 's.emp_id', fixed_select, flags=re.I)
            fixed_select = re.sub(r'(?<!\.)\bbasic_salary\b', 's.basic_salary', fixed_select, flags=re.I)
            fixed_select = re.sub(r'(?<!\.)\bbonus\b', 's.bonus', fixed_select, flags=re.I)
            fixed_select = re.sub(r'(?<!\.)\beffective_date\b', 's.effective_date', fixed_select, flags=re.I)
            fixed_select = re.sub(r'(?<!\.)\bemp_name\b', 'e.emp_name', fixed_select, flags=re.I)

            fixed_rest = re.sub(
                r'(?<!\.)\b(emp_id|basic_salary|bonus|effective_date)\b',
                r's.\1',
                rest,
                flags=re.I,
            )

            sql = f"SELECT {fixed_select} FROM salaries s JOIN employees e ON e.emp_id = s.emp_id{fixed_rest}"

    return sql
